[colors.bright]
black = "0x444b6a"
blue = "0x7da6ff"
cyan = "0x0db9d7"
green = "0xb9f27c"
magenta = "0xbb9af7"
red = "0xff7a93"
white = "0xacb0d0"
yellow = "0xff9e64"

[colors.normal]
black = "0x32344a"
blue = "0x7aa2f7"
cyan = "0x449dab"
green = "0x9ece6a"
magenta = "0xad8ee6"
red = "0xf7768e"
white = "0x9699a8"
yellow = "0xe0af68"

[colors.primary]
background = "0x24283b"
foreground = "0xa9b1d6"

# [schemes.gotham.bright]
# black = "0x10151b"
# blue = "0x097788"
# cyan = "0x599caa"
# green = "0x384f5d"
# magenta = "0x888ba5"
# red = "0xd26939"
# white = "0xd3ebe9"
# yellow = "0x245361"

# [schemes.gotham.normal]
# black = "0x0a0f14"
# blue = "0x498065"
# cyan = "0x33859d"
# green = "0x26a98b"
# magenta = "0x4e5165"
# red = "0xc33027"
# white = "0x98d1ce"
# yellow = "0xedb54b"

# [schemes.gotham.primary]
# background = "0x0a0f14"
# foreground = "0x98d1ce"

# [schemes.tokyo-night-storm.bright]
# black = "0x444b6a"
# blue = "0x7da6ff"
# cyan = "0x0db9d7"
# green = "0xb9f27c"
# magenta = "0xbb9af7"
# red = "0xff7a93"
# white = "0xacb0d0"
# yellow = "0xff9e64"

# [schemes.tokyo-night-storm.normal]
# black = "0x32344a"
# blue = "0x7aa2f7"
# cyan = "0x449dab"
# green = "0x9ece6a"
# magenta = "0xad8ee6"
# red = "0xf7768e"
# white = "0x9699a8"
# yellow = "0xe0af68"

# [schemes.tokyo-night-storm.primary]
# background = "0x24283b"
# foreground = "0xa9b1d6"

# [schemes.tomorrowNightBright.bright]
# black = "0x666666"
# blue = "0x7aa6da"
# cyan = "0x54ced6"
# green = "0x9ec400"
# magenta = "0xb77ee0"
# red = "0xff3334"
# white = "0xffffff"
# yellow = "0xe7c547"

# [schemes.tomorrowNightBright.cursor]
# cursor = "0x00ff88"

# [schemes.tomorrowNightBright.dim]
# black = "0x000000"
# blue = "0x506d8f"
# cyan = "0x497e7a"
# green = "0x7a8530"
# magenta = "0x80638e"
# red = "0x8c3336"
# white = "0x9a9a9a"
# yellow = "0x97822e"

# [schemes.tomorrowNightBright.normal]
# black = "0x000000"
# blue = "0x7aa6da"
# cyan = "0x70c0ba"
# green = "0xb9ca4a"
# magenta = "0xc397d8"
# red = "0xd54e53"
# white = "0xeaeaea"
# yellow = "0xe6c547"

# [schemes.tomorrowNightBright.primary]
# background = "0x000000"
# foreground = "0x00979a"
